# Generated by Django 2.0 on 2018-10-30 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_serie_favorites_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='alerts_seen',
            field=models.NullBooleanField(default=False),
        ),
    ]
