# Generated by Django 2.0 on 2018-10-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('API_KEY', models.CharField(default='e403e0e25456da8a7d4727d3139f0d88', max_length=500)),
                ('query', models.CharField(max_length=400, null=True, verbose_name='Search')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('nb_episodes', models.IntegerField(verbose_name='Total number of episodes')),
                ('nb_seasons', models.IntegerField(verbose_name='Total number of seasons')),
                ('genres', models.TextField()),
                ('overview', models.TextField(null=True)),
                ('last_episode_date', models.DateTimeField(null=True, verbose_name='Date of last episode')),
                ('last_episode', models.CharField(max_length=10, null=True, verbose_name='Last episode')),
                ('next_episode_date', models.DateTimeField(null=True, verbose_name='Date of next episode')),
                ('next_episode', models.CharField(max_length=10, null=True, verbose_name='Next episode')),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
            },
        ),
    ]
