# Generated by Django 2.0 on 2018-10-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20181028_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='serie',
            name='favorites_user',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
