# Generated by Django 2.0 on 2018-11-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20181104_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='alert',
            field=models.IntegerField(default=999999, verbose_name='Days before next episode'),
        ),
    ]
