# Generated by Django 2.0 on 2018-11-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20181104_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serie',
            name='alert',
            field=models.IntegerField(blank=True, default=999999, null=True, verbose_name='Days before next episode'),
        ),
    ]
