# Generated by Django 2.0 on 2018-11-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20181105_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='favorites_user',
        ),
        migrations.RemoveField(
            model_name='serie',
            name='serie_id',
        ),
        migrations.AddField(
            model_name='serie',
            name='nb_fav_users',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
